kind: pipeline
name: Mystic Kernel (MSM-4.19)

steps:
- name: Building Mystic Kernel
  image: okta10/docker:ubuntu
  environment: 
    TOKED:
      from_secret: TOKED
    TELEGRAM_TOKEN:
      from_secret: TELEGRAM_TOKEN
    CHANNEL_ID:
      from_secret: CHANNEL_ID

  commands:
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.19/doStart"
    - bash doStart beta
    - cd kernel
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.19/doBuild"
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.19/doPush"
    - bash doBuild whyred
    - bash doBuild a26x
    - bash doBuild lavender
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/patch/oc_4.19.patch"
    - git apply oc_4.19.patch
    - bash doBuild whyred oc
    - bash doPush beta
