kind: pipeline
name: Mystic Kernel (MSM-4.4)

steps:
- name: Building Mystic Kernel
  image: okta10/docker:ubuntu
  environment: 
    TOKED:
      from_secret: TOKED
    TELEGRAM_TOKEN:
      from_secret: TELEGRAM_TOKEN
    CHANNEL_ID:
      from_secret: CHANNEL_ID

  commands:
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doStart"
    - bash doStart beta gcc
    - cd kernel
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doPush"
    - bash build a26x newcam gcc
    - bash build a26x oldcam gcc
    - bash build a26x tencam gcc
    - bash build lavender newcam gcc
    - bash build lavender oldcam gcc
    - bash build lavender qtihaptics gcc
    - bash build tulip newcam gcc
    - bash build tulip oldcam gcc
    - bash build whyred newcam gcc
    - bash build whyred oldcam gcc
    - bash build whyred qtihaptics gcc
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/patch/oc_4.4.patch"
    - git apply oc_4.4.patch
    - bash build tulip newcam oc gcc
    - bash build tulip oldcam oc gcc
    - bash build whyred newcam oc gcc
    - bash build whyred oldcam oc gcc
    - bash build whyred qtihaptics oc gcc
    - bash doPush beta gcc
