kind: pipeline
name: Mystic Kernel (MSM-4.19)

steps:
- name: Building Mystic Kernel
  image: okta10/docker:debian
  environment: 
    TOKED:
      from_secret: TOKED
    TELEGRAM_TOKEN:
      from_secret: TELEGRAM_TOKEN
    CHANNEL_ID:
      from_secret: CHANNEL_ID

  commands:
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.19/doStart.sh"
    - bash doStart.sh beta clang
    - cd kernel
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.19/doPush.sh"
    - bash doBuild.sh a26x clang
    - bash doBuild.sh lavender clang
    - bash doBuild.sh whyred clang
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/patch/oc_4.19.patch"
    - git apply oc_4.19.patch
    - bash doBuild.sh whyred oc clang
    - bash doPush.sh clang
