kind: pipeline
name: Mystic Kernel (MSM-4.19)

steps:
- name: Building Mystic Kernel
  image: okta10/docker:debian
  environment: 
    TOKED:
      from_secret: TOKED
    TELEGRAM_TOKEN:
      from_secret: TELEGRAM_TOKEN
    CHANNEL_ID:
      from_secret: CHANNEL_ID

  commands:
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.19/doStart"
    - bash doStart beta gcc
    - cd kernel
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.19/doPush"
    - bash build a26x gcc
    - bash build lavender gcc
    - bash build whyred gcc
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/patch/oc_4.19.patch"
    - git apply oc_4.19.patch
    - bash build whyred oc gcc
    - bash doPush beta gcc
