kind: pipeline
name: Mystic Kernel (MSM-4.4)

steps:
- name: Building Mystic Kernel
  image: okta10/docker:ubuntu
  environment: 
    TOKED:
      from_secret: TOKED
    TELEGRAM_TOKEN:
      from_secret: TELEGRAM_TOKEN
    CHANNEL_ID:
      from_secret: CHANNEL_ID

  commands:
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doStart"
    - bash doStart beta
    - cd kernel
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doPush"
    - bash build whyred oldcam
    - bash build whyred newcam
    - bash build tulip oldcam
    - bash build tulip newcam
    - bash build lavender oldcam
    - bash build lavender newcam
    - bash build a26x oldcam
    - bash build a26x newcam
    - bash build a26x tencam
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/patch/oc_4.4.patch"
    - git apply oc_4.4.patch
    - bash build whyred oldcam oc
    - bash build whyred newcam oc
    - bash build tulip oldcam oc
    - bash build tulip newcam oc
    - bash doPush beta