kind: pipeline
name: Mystic Kernel (MSM-4.4)

steps:
- name: Building Mystic Kernel
  image: okta10/docker:ubuntu
  environment: 
    TOKED:
      from_secret: TOKED
    TELEGRAM_TOKEN:
      from_secret: TELEGRAM_TOKEN
    CHANNEL_ID:
      from_secret: CHANNEL_ID

  commands:
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doStart.sh"
    - bash doStart.sh beta clang
    - cd kernel
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doPush.sh"
    - bash doBuild.sh a26x newcam clang
    - bash doBuild.sh a26x oldcam clang
    - bash doBuild.sh a26x tencam clang
    - bash doBuild.sh lavender newcam clang
    - bash doBuild.sh lavender oldcam clang
    - bash doBuild.sh tulip newcam clang
    - bash doBuild.sh tulip oldcam clang
    - bash doBuild.sh whyred newcam clang
    - bash doBuild.sh whyred oldcam clang
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/patch/oc_4.4.patch"
    - git apply oc_4.4.patch
    - bash doBuild.sh tulip newcam oc clang
    - bash doBuild.sh tulip oldcam oc clang
    - bash doBuild.sh whyred newcam oc clang
    - bash doBuild.sh whyred oldcam oc clang
    - bash doPush.sh clang
