kind: pipeline
name: Mystic Kernel (MSM-4.4)

steps:
- name: Building Mystic Kernel
  image: okta10/docker:latest
  environment: 
    TOKED:
      from_secret: TOKED
    TELEGRAM_TOKEN:
      from_secret: TELEGRAM_TOKEN
    CHANNEL_ID:
      from_secret: CHANNEL_ID

  commands:
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doStart"
    - bash doStart beta
    - cd kernel
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doBuild"
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doPush"
    - bash doBuild whyredoldcam beta
    - bash doBuild whyrednewcam beta
    - bash doBuild tulipoldcam beta
    - bash doBuild tulipnewcam beta
    - bash doBuild lavenderoldcam beta
    - bash doBuild lavendernewcam beta
    - bash doBuild a26xoldcam beta
    - bash doBuild a26xnewcam beta
    - bash doBuild a26xtencam beta
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/patch/oc_4.4.patch"
    - git apply oc_4.4.patch
    - bash doBuild ocwhyredold beta
    - bash doBuild ocwhyrednew beta
    - bash doBuild octulipold beta
    - bash doBuild octulipnew beta
    - bash doPush beta