kind: pipeline
name: Mystic Kernel (MSM-4.4)

steps:
- name: Building Mystic Kernel
  image: okta10/docker:ubuntu
  environment: 
    GH_TOKEN:
      from_secret: GH_TOKEN
    TG_BOT_TOKEN:
      from_secret: TG_BOT_TOKEN
    TG_CHAT_ID:
      from_secret: TG_CHAT_ID

  commands:
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doStart.sh"
    - bash doStart.sh beta clang
    - cd kernel
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doBuild_dtb.sh"
    - bash doBuild_dtb.sh a26x clang qpnp
    - bash doBuild_dtb.sh lavender clang qpnp
    - bash doBuild_dtb.sh tulip clang qpnp
    - bash doBuild_dtb.sh whyred clang qpnp
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/patch/qti_haptic.patch"
    - git apply qti_haptic.patch
    - bash doBuild_dtb.sh a26x clang qti
    - bash doBuild_dtb.sh lavender clang qti
    - bash doBuild_dtb.sh tulip clang qti
    - bash doBuild_dtb.sh whyred clang qti
    - git restore .
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doBuild.sh"
    - bash doBuild.sh a26x newcam clang
    - bash doBuild.sh a26x oldcam clang
    - bash doBuild.sh a26x tencam clang
    - bash doBuild.sh lavender newcam clang
    - bash doBuild.sh lavender oldcam clang
    - bash doBuild.sh tulip newcam clang
    - bash doBuild.sh tulip oldcam clang
    - bash doBuild.sh whyred newcam clang
    - bash doBuild.sh whyred oldcam clang
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doFinal.sh"
    - bash doFinal.sh clang
