kind: pipeline
name: Mystic Kernel (MSM-4.14)

steps:
- name: Building Mystic Kernel
  image: okta10/docker:ubuntu
  environment: 
    GH_TOKEN:
      from_secret: GH_TOKEN
    TG_BOT_TOKEN:
      from_secret: TG_BOT_TOKEN
    TG_CHAT_ID:
      from_secret: TG_CHAT_ID

  commands:
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.14/doBuild.sh"
    - bash doBuild.sh stable gcc
