kind: pipeline
name: Mystic Kernel (MSM-4.4)

steps:
- name: Building Mystic Kernel
  image: okta10/docker:latest
  environment: 
    TOKED:
      from_secret: TOKED
    TELEGRAM_TOKEN:
      from_secret: TELEGRAM_TOKEN
    CHANNEL_ID:
      from_secret: CHANNEL_ID

  commands:
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doStart"
    - bash doStart beta
    - cd kernel
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doBuild"
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doPush"
    - bash doBuild whyred oldcam
    - bash doBuild whyred newcam
    - bash doBuild tulip oldcam
    - bash doBuild tulip newcam
    - bash doBuild lavender oldcam
    - bash doBuild lavender newcam
    - bash doBuild a26x oldcam
    - bash doBuild a26x newcam
    - bash doBuild a26x tencam
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/patch/oc_4.4.patch"
    - git apply oc_4.4.patch
    - bash doBuild whyred oldcam oc
    - bash doBuild whyred newcam oc
    - bash doBuild tulip oldcam oc
    - bash doBuild tulip newcam oc
    - bash doPush beta