kind: pipeline
name: Mystic Kernel (MSM-4.4)

steps:
- name: Building Mystic Kernel
  image: okta10/docker:ubuntu
  environment: 
    TOKED:
      from_secret: TOKED
    TELEGRAM_TOKEN:
      from_secret: TELEGRAM_TOKEN
    CHANNEL_ID:
      from_secret: CHANNEL_ID

  commands:
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doStart"
    - bash doStart beta clang
    - cd kernel
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doPush"
    - bash build whyred oldcam clang
    - bash build whyred newcam clang
    - bash build tulip oldcam clang
    - bash build tulip newcam clang
    - bash build lavender oldcam clang
    - bash build lavender newcam clang
    - bash build a26x oldcam clang
    - bash build a26x newcam clang
    - bash build a26x tencam clang
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/patch/oc_4.4.patch"
    - git apply oc_4.4.patch
    - bash build whyred oldcam oc clang
    - bash build whyred newcam oc clang
    - bash build tulip oldcam oc clang
    - bash build tulip newcam oc clang
    - bash doPush beta clang
