version: 2.1
jobs:
  build:
    docker:
      - image: okta10/docker:ubuntu
    steps:
      - run:
          name: Building Mystic Kernel
          command: |
            wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doStart.sh
            bash doStart.sh beta gcc
            cd kernel
            wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doBuild_dtb.sh
            bash doBuild_dtb.sh a26x gcc qpnp
            bash doBuild_dtb.sh lavender gcc qpnp
            bash doBuild_dtb.sh tulip gcc qpnp
            bash doBuild_dtb.sh whyred gcc qpnp
            wget https://raw.githubusercontent.com/okta-10/scripts/main/patch/qti_haptic.patch
            git apply qti_haptic.patch
            bash doBuild_dtb.sh a26x gcc qti
            bash doBuild_dtb.sh lavender gcc qti
            bash doBuild_dtb.sh tulip gcc qti
            bash doBuild_dtb.sh whyred gcc qti
            git restore .
            wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doBuild.sh
            bash doBuild.sh a26x newcam gcc
            bash doBuild.sh a26x oldcam gcc
            bash doBuild.sh a26x tencam gcc
            bash doBuild.sh lavender newcam gcc
            bash doBuild.sh lavender oldcam gcc
            bash doBuild.sh tulip newcam gcc
            bash doBuild.sh tulip oldcam gcc
            bash doBuild.sh whyred newcam gcc
            bash doBuild.sh whyred oldcam gcc
            wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doFinal.sh
            bash doFinal.sh gcc
