version: 2.1
jobs:
  build:
    docker:
      - image: okta10/docker:ubuntu
    steps:
      - run: git clone --depth=1 https://github.com/okta-10/mystic_kernel_sdm660-4.4.git -b Mystic-4.4 .
      - run: wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doStart
      - run: bash doStart clang
      - run: cd kernel
      - run: wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doBuild
      - run: wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doPush
      - run: bash doBuild whyred oldcam clang
      - run: bash doBuild whyred newcam clang
      - run: bash doBuild tulip oldcam clang
      - run: bash doBuild tulip newcam clang
      - run: bash doBuild lavender oldcam clang
      - run: bash doBuild lavender newcam clang
      - run: bash doBuild a26x oldcam clang
      - run: bash doBuild a26x newcam clang
      - run: bash doBuild a26x tencam clang
      - run: wget https://raw.githubusercontent.com/okta-10/scripts/main/patch/oc_4.4.patch
      - run: git apply oc_4.4.patch
      - run: bash doBuild whyred oldcam oc clang
      - run: bash doBuild whyred newcam oc clang
      - run: bash doBuild tulip oldcam oc clang
      - run: bash doBuild tulip newcam oc clang
      - run: bash doPush clang
