version: 2.1
jobs:
  build:
    docker:
      - image: okta10/docker:ubuntu
    steps:
      - run:
          name: Building Mystic Kernel
          command: |
            wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doStart.sh
            bash doStart.sh beta gcc
            cd kernel
            wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doBuild.sh
            bash doBuild.sh a26x newcam gcc
            bash doBuild.sh a26x oldcam gcc
            bash doBuild.sh a26x tencam gcc
            bash doBuild.sh lavender newcam gcc
            bash doBuild.sh lavender oldcam gcc
            bash doBuild.sh tulip newcam gcc
            bash doBuild.sh tulip oldcam gcc
            bash doBuild.sh whyred newcam gcc
            bash doBuild.sh whyred oldcam gcc
            wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doFinal.sh
            bash doFinal.sh gcc
