version: 2.1
jobs:
  build:
    docker:
      - image: okta10/docker:ubuntu
    steps:
      - run: git clone --depth=1 https://"${TOKED}":x-oauth-basic@github.com/okta-10/mystic-beta.git -b Mystic-4.4 .
      - run: wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doStart.sh
      - run: bash doStart.sh clang
      - run: cd kernel
      - run: wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doPush.sh
      - run: bash doBuild.sh a26x newcam clang
      - run: bash doBuild.sh a26x oldcam clang
      - run: bash doBuild.sh a26x tencam clang
      - run: bash doBuild.sh lavender newcam clang
      - run: bash doBuild.sh lavender oldcam clang
      - run: bash doBuild.sh tulip newcam clang
      - run: bash doBuild.sh tulip oldcam clang
      - run: bash doBuild.sh whyred newcam clang
      - run: bash doBuild.sh whyred oldcam clang
      - run: wget https://raw.githubusercontent.com/okta-10/scripts/main/patch/oc_4.4.patch
      - run: git apply oc_4.4.patch
      - run: bash doBuild.sh tulip newcam oc clang
      - run: bash doBuild.sh tulip oldcam oc clang
      - run: bash doBuild.sh whyred newcam oc clang
      - run: bash doBuild.sh whyred oldcam oc clang
      - run: bash doPush.sh clang
