version: 2.1
jobs:
  build:
    docker:
      - image: okta10/docker:ubuntu
    steps:
      - run: git clone --depth=1 https://github.com/okta-10/mystic_kernel_sdm660-4.4.git -b Mystic-4.4 .
      - run: wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doStart
      - run: bash doStart
      - run: cd kernel
      - run: wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doBuild
      - run: wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doPush
      - run: bash doBuild whyred oldcam
      - run: bash doBuild whyred newcam
      - run: bash doBuild tulip oldcam
      - run: bash doBuild tulip newcam
      - run: bash doBuild lavender oldcam
      - run: bash doBuild lavender newcam
      - run: bash doBuild a26x oldcam
      - run: bash doBuild a26x newcam
      - run: bash doBuild a26x tencam
      - run: wget https://raw.githubusercontent.com/okta-10/scripts/main/patch/oc_4.4.patch
      - run: git apply oc_4.4.patch
      - run: bash doBuild whyred oldcam oc
      - run: bash doBuild whyred newcam oc
      - run: bash doBuild tulip oldcam oc
      - run: bash doBuild tulip newcam oc
      - run: bash doPush
